apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"ryu-deployment","namespace":"default"},"spec":{"replicas":2,"template":{"metadata":{"labels":{"app":"ryu"}},"spec":{"containers":[{"args":["ryu-manager","./ryu/ryu/app/simple_switch_13.py"],"image":"osrg/ryu","name":"ryu","ports":[{"containerPort":6653,"name":"openflow"}],"resources":{"limits":{"cpu":"300m","memory":"128Mi"}}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: ryu
  name: ryu-deployment
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ryu-deployment
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ryu
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ryu
    spec:
      containers:
      - image: vval/simple_switch:latest
        imagePullPolicy: Always
        name: ryu
        ports:
        - containerPort: 6653
          name: openflow
          protocol: TCP
        - containerPort: 6633
          name: of-legacy
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
